<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>10</LangVersion>
    <AssemblyName>GsoundStageFieldBridge</AssemblyName>
    <RootNamespace>GsoundStageFieldBridge</RootNamespace>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Plugin.cs" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="0Harmony"><HintPath>$(GameRoot)\BepInEx\core\0Harmony.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="AsmResolver"><HintPath>$(GameRoot)\BepInEx\core\AsmResolver.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="AsmResolver.DotNet"><HintPath>$(GameRoot)\BepInEx\core\AsmResolver.DotNet.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="AsmResolver.PE"><HintPath>$(GameRoot)\BepInEx\core\AsmResolver.PE.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="AsmResolver.PE.File"><HintPath>$(GameRoot)\BepInEx\core\AsmResolver.PE.File.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="AssetRipper.CIL"><HintPath>$(GameRoot)\BepInEx\core\AssetRipper.CIL.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="AssetRipper.Primitives"><HintPath>$(GameRoot)\BepInEx\core\AssetRipper.Primitives.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="BepInEx.Core"><HintPath>$(GameRoot)\BepInEx\core\BepInEx.Core.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="BepInEx.Preloader.Core"><HintPath>$(GameRoot)\BepInEx\core\BepInEx.Preloader.Core.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="BepInEx.Unity.Common"><HintPath>$(GameRoot)\BepInEx\core\BepInEx.Unity.Common.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="BepInEx.Unity.IL2CPP"><HintPath>$(GameRoot)\BepInEx\core\BepInEx.Unity.IL2CPP.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Cpp2IL.Core"><HintPath>$(GameRoot)\BepInEx\core\Cpp2IL.Core.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Disarm"><HintPath>$(GameRoot)\BepInEx\core\Disarm.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="dobby"><HintPath>$(GameRoot)\BepInEx\core\dobby.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Gee.External.Capstone"><HintPath>$(GameRoot)\BepInEx\core\Gee.External.Capstone.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Iced"><HintPath>$(GameRoot)\BepInEx\core\Iced.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Il2CppInterop.Common"><HintPath>$(GameRoot)\BepInEx\core\Il2CppInterop.Common.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Il2CppInterop.Generator"><HintPath>$(GameRoot)\BepInEx\core\Il2CppInterop.Generator.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Il2CppInterop.HarmonySupport"><HintPath>$(GameRoot)\BepInEx\core\Il2CppInterop.HarmonySupport.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Il2CppInterop.Runtime"><HintPath>$(GameRoot)\BepInEx\core\Il2CppInterop.Runtime.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="LibCpp2IL"><HintPath>$(GameRoot)\BepInEx\core\LibCpp2IL.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Mono.Cecil"><HintPath>$(GameRoot)\BepInEx\core\Mono.Cecil.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Mono.Cecil.Mdb"><HintPath>$(GameRoot)\BepInEx\core\Mono.Cecil.Mdb.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Mono.Cecil.Pdb"><HintPath>$(GameRoot)\BepInEx\core\Mono.Cecil.Pdb.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Mono.Cecil.Rocks"><HintPath>$(GameRoot)\BepInEx\core\Mono.Cecil.Rocks.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="MonoMod.Backports"><HintPath>$(GameRoot)\BepInEx\core\MonoMod.Backports.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="MonoMod.ILHelpers"><HintPath>$(GameRoot)\BepInEx\core\MonoMod.ILHelpers.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="MonoMod.RuntimeDetour"><HintPath>$(GameRoot)\BepInEx\core\MonoMod.RuntimeDetour.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="MonoMod.Utils"><HintPath>$(GameRoot)\BepInEx\core\MonoMod.Utils.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="SemanticVersioning"><HintPath>$(GameRoot)\BepInEx\core\SemanticVersioning.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="StableNameDotNet"><HintPath>$(GameRoot)\BepInEx\core\StableNameDotNet.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="WasmDisassembler"><HintPath>$(GameRoot)\BepInEx\core\WasmDisassembler.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="__Generated"><HintPath>$(GameRoot)\BepInEx\interop\__Generated.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="ACTk.Examples.Genuine.Runtime"><HintPath>$(GameRoot)\BepInEx\interop\ACTk.Examples.Genuine.Runtime.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="ACTk.Examples.Runtime"><HintPath>$(GameRoot)\BepInEx\interop\ACTk.Examples.Runtime.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="ACTk.Runtime"><HintPath>$(GameRoot)\BepInEx\interop\ACTk.Runtime.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="AllIn1SpriteShaderAssembly"><HintPath>$(GameRoot)\BepInEx\interop\AllIn1SpriteShaderAssembly.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Assembly-CSharp-firstpass"><HintPath>$(GameRoot)\BepInEx\interop\Assembly-CSharp-firstpass.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Assembly-CSharp"><HintPath>$(GameRoot)\BepInEx\interop\Assembly-CSharp.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Cinemachine"><HintPath>$(GameRoot)\BepInEx\interop\Cinemachine.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Coffee.SoftMaskForUGUI"><HintPath>$(GameRoot)\BepInEx\interop\Coffee.SoftMaskForUGUI.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="CommonAssembly"><HintPath>$(GameRoot)\BepInEx\interop\CommonAssembly.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="DOTween"><HintPath>$(GameRoot)\BepInEx\interop\DOTween.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="DOTweenPro"><HintPath>$(GameRoot)\BepInEx\interop\DOTweenPro.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Facepunch.Steamworks.Win64"><HintPath>$(GameRoot)\BepInEx\interop\Facepunch.Steamworks.Win64.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Febucci.TextAnimator.Demo.Runtime"><HintPath>$(GameRoot)\BepInEx\interop\Febucci.TextAnimator.Demo.Runtime.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Febucci.TextAnimator.Runtime"><HintPath>$(GameRoot)\BepInEx\interop\Febucci.TextAnimator.Runtime.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Firebase.App"><HintPath>$(GameRoot)\BepInEx\interop\Firebase.App.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Firebase.Crashlytics"><HintPath>$(GameRoot)\BepInEx\interop\Firebase.Crashlytics.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Firebase.Platform"><HintPath>$(GameRoot)\BepInEx\interop\Firebase.Platform.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="FMODUnity"><HintPath>$(GameRoot)\BepInEx\interop\FMODUnity.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="FMODUnityResonance"><HintPath>$(GameRoot)\BepInEx\interop\FMODUnityResonance.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Il2CppMono.Security"><HintPath>$(GameRoot)\BepInEx\interop\Il2CppMono.Security.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Il2Cppmscorlib"><HintPath>$(GameRoot)\BepInEx\interop\Il2Cppmscorlib.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Il2CppSystem.Configuration"><HintPath>$(GameRoot)\BepInEx\interop\Il2CppSystem.Configuration.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Il2CppSystem.Core"><HintPath>$(GameRoot)\BepInEx\interop\Il2CppSystem.Core.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Il2CppSystem.Data"><HintPath>$(GameRoot)\BepInEx\interop\Il2CppSystem.Data.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Il2CppSystem"><HintPath>$(GameRoot)\BepInEx\interop\Il2CppSystem.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Il2CppSystem.Drawing"><HintPath>$(GameRoot)\BepInEx\interop\Il2CppSystem.Drawing.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Il2CppSystem.IO.Compression"><HintPath>$(GameRoot)\BepInEx\interop\Il2CppSystem.IO.Compression.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Il2CppSystem.IO.Compression.FileSystem"><HintPath>$(GameRoot)\BepInEx\interop\Il2CppSystem.IO.Compression.FileSystem.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Il2CppSystem.Net.Http"><HintPath>$(GameRoot)\BepInEx\interop\Il2CppSystem.Net.Http.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Il2CppSystem.Numerics"><HintPath>$(GameRoot)\BepInEx\interop\Il2CppSystem.Numerics.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Il2CppSystem.Runtime.CompilerServices.Unsafe"><HintPath>$(GameRoot)\BepInEx\interop\Il2CppSystem.Runtime.CompilerServices.Unsafe.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Il2CppSystem.Runtime.Serialization"><HintPath>$(GameRoot)\BepInEx\interop\Il2CppSystem.Runtime.Serialization.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Il2CppSystem.ServiceModel.Internals"><HintPath>$(GameRoot)\BepInEx\interop\Il2CppSystem.ServiceModel.Internals.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Il2CppSystem.Text.Encodings.Web"><HintPath>$(GameRoot)\BepInEx\interop\Il2CppSystem.Text.Encodings.Web.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Il2CppSystem.Text.Json"><HintPath>$(GameRoot)\BepInEx\interop\Il2CppSystem.Text.Json.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Il2CppSystem.Xml"><HintPath>$(GameRoot)\BepInEx\interop\Il2CppSystem.Xml.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Il2CppSystem.Xml.Linq"><HintPath>$(GameRoot)\BepInEx\interop\Il2CppSystem.Xml.Linq.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="InterfacesLibraryAssembly"><HintPath>$(GameRoot)\BepInEx\interop\InterfacesLibraryAssembly.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="LimbusCompany.AddressableConstants"><HintPath>$(GameRoot)\BepInEx\interop\LimbusCompany.AddressableConstants.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="LokoSolo.PinchableScrollRect"><HintPath>$(GameRoot)\BepInEx\interop\LokoSolo.PinchableScrollRect.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="material-timeline"><HintPath>$(GameRoot)\BepInEx\interop\material-timeline.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Newtonsoft.Json"><HintPath>$(GameRoot)\BepInEx\interop\Newtonsoft.Json.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="ProjectMoon.BaseStructures"><HintPath>$(GameRoot)\BepInEx\interop\ProjectMoon.BaseStructures.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="ProjectMoon.DelegateCollection"><HintPath>$(GameRoot)\BepInEx\interop\ProjectMoon.DelegateCollection.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="ProjectMoonUnity.Utils"><HintPath>$(GameRoot)\BepInEx\interop\ProjectMoonUnity.Utils.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Purchasing.Common"><HintPath>$(GameRoot)\BepInEx\interop\Purchasing.Common.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="RubyTextMeshPro"><HintPath>$(GameRoot)\BepInEx\interop\RubyTextMeshPro.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="sc.posteffects.runtime"><HintPath>$(GameRoot)\BepInEx\interop\sc.posteffects.runtime.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="SkillViewMarker"><HintPath>$(GameRoot)\BepInEx\interop\SkillViewMarker.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="SocketIOUnityAssembly"><HintPath>$(GameRoot)\BepInEx\interop\SocketIOUnityAssembly.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="spine-csharp"><HintPath>$(GameRoot)\BepInEx\interop\spine-csharp.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="spine-timeline"><HintPath>$(GameRoot)\BepInEx\interop\spine-timeline.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="spine-unity"><HintPath>$(GameRoot)\BepInEx\interop\spine-unity.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Timeline.Samples.Annotation"><HintPath>$(GameRoot)\BepInEx\interop\Timeline.Samples.Annotation.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Timeline.Samples.Text"><HintPath>$(GameRoot)\BepInEx\interop\Timeline.Samples.Text.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Timeline.Samples.TimeDilation"><HintPath>$(GameRoot)\BepInEx\interop\Timeline.Samples.TimeDilation.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Timeline.Samples.Tween"><HintPath>$(GameRoot)\BepInEx\interop\Timeline.Samples.Tween.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Timeline.Samples.Utilities"><HintPath>$(GameRoot)\BepInEx\interop\Timeline.Samples.Utilities.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Timeline.Samples.Video"><HintPath>$(GameRoot)\BepInEx\interop\Timeline.Samples.Video.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UIEffect"><HintPath>$(GameRoot)\BepInEx\interop\UIEffect.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UniTask.Addressables"><HintPath>$(GameRoot)\BepInEx\interop\UniTask.Addressables.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UniTask"><HintPath>$(GameRoot)\BepInEx\interop\UniTask.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UniTask.DOTween"><HintPath>$(GameRoot)\BepInEx\interop\UniTask.DOTween.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.2D.Animation.Runtime"><HintPath>$(GameRoot)\BepInEx\interop\Unity.2D.Animation.Runtime.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.2D.Common.Runtime"><HintPath>$(GameRoot)\BepInEx\interop\Unity.2D.Common.Runtime.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.2D.SpriteShape.Runtime"><HintPath>$(GameRoot)\BepInEx\interop\Unity.2D.SpriteShape.Runtime.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.Addressables"><HintPath>$(GameRoot)\BepInEx\interop\Unity.Addressables.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.Burst"><HintPath>$(GameRoot)\BepInEx\interop\Unity.Burst.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.Burst.Unsafe"><HintPath>$(GameRoot)\BepInEx\interop\Unity.Burst.Unsafe.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.Collections"><HintPath>$(GameRoot)\BepInEx\interop\Unity.Collections.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.Collections.LowLevel.ILSupport"><HintPath>$(GameRoot)\BepInEx\interop\Unity.Collections.LowLevel.ILSupport.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.InternalAPIEngineBridge.001"><HintPath>$(GameRoot)\BepInEx\interop\Unity.InternalAPIEngineBridge.001.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.InternalAPIEngineBridge.004"><HintPath>$(GameRoot)\BepInEx\interop\Unity.InternalAPIEngineBridge.004.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.Mathematics"><HintPath>$(GameRoot)\BepInEx\interop\Unity.Mathematics.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.MemoryProfiler"><HintPath>$(GameRoot)\BepInEx\interop\Unity.MemoryProfiler.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.ProBuilder"><HintPath>$(GameRoot)\BepInEx\interop\Unity.ProBuilder.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.ProBuilder.KdTree"><HintPath>$(GameRoot)\BepInEx\interop\Unity.ProBuilder.KdTree.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.ProBuilder.Poly2Tri"><HintPath>$(GameRoot)\BepInEx\interop\Unity.ProBuilder.Poly2Tri.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.RenderPipeline.Universal.ShaderLibrary"><HintPath>$(GameRoot)\BepInEx\interop\Unity.RenderPipeline.Universal.ShaderLibrary.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.RenderPipelines.Core.Runtime"><HintPath>$(GameRoot)\BepInEx\interop\Unity.RenderPipelines.Core.Runtime.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.RenderPipelines.Core.Runtime.Shared"><HintPath>$(GameRoot)\BepInEx\interop\Unity.RenderPipelines.Core.Runtime.Shared.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.RenderPipelines.GPUDriven.Runtime"><HintPath>$(GameRoot)\BepInEx\interop\Unity.RenderPipelines.GPUDriven.Runtime.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.RenderPipelines.Universal.2D.Runtime"><HintPath>$(GameRoot)\BepInEx\interop\Unity.RenderPipelines.Universal.2D.Runtime.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.RenderPipelines.Universal.Runtime"><HintPath>$(GameRoot)\BepInEx\interop\Unity.RenderPipelines.Universal.Runtime.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.ResourceManager"><HintPath>$(GameRoot)\BepInEx\interop\Unity.ResourceManager.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.Services.Core.Configuration"><HintPath>$(GameRoot)\BepInEx\interop\Unity.Services.Core.Configuration.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.Services.Core.Device"><HintPath>$(GameRoot)\BepInEx\interop\Unity.Services.Core.Device.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.Services.Core"><HintPath>$(GameRoot)\BepInEx\interop\Unity.Services.Core.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.Services.Core.Environments"><HintPath>$(GameRoot)\BepInEx\interop\Unity.Services.Core.Environments.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.Services.Core.Environments.Internal"><HintPath>$(GameRoot)\BepInEx\interop\Unity.Services.Core.Environments.Internal.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.Services.Core.Internal"><HintPath>$(GameRoot)\BepInEx\interop\Unity.Services.Core.Internal.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.Services.Core.Registration"><HintPath>$(GameRoot)\BepInEx\interop\Unity.Services.Core.Registration.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.Services.Core.Scheduler"><HintPath>$(GameRoot)\BepInEx\interop\Unity.Services.Core.Scheduler.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.Services.Core.Telemetry"><HintPath>$(GameRoot)\BepInEx\interop\Unity.Services.Core.Telemetry.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.Services.Core.Threading"><HintPath>$(GameRoot)\BepInEx\interop\Unity.Services.Core.Threading.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.TextMeshPro"><HintPath>$(GameRoot)\BepInEx\interop\Unity.TextMeshPro.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.Timeline"><HintPath>$(GameRoot)\BepInEx\interop\Unity.Timeline.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.UnifiedRayTracing.Runtime"><HintPath>$(GameRoot)\BepInEx\interop\Unity.UnifiedRayTracing.Runtime.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.AccessibilityModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.AccessibilityModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.AdaptivePerformanceModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.AdaptivePerformanceModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.AIModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.AIModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.AndroidJNIModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.AndroidJNIModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.AnimationModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.AnimationModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.AssetBundleModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.AssetBundleModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.AudioModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.AudioModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.ClothModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.ClothModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.ClusterInputModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.ClusterInputModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.ClusterRendererModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.ClusterRendererModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.ContentLoadModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.ContentLoadModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.CoreModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.CrashReportingModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.CrashReportingModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.DirectorModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.DirectorModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.DSPGraphModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.DSPGraphModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.GameCenterModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.GameCenterModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.GIModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.GIModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.GraphicsStateCollectionSerializerModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.GraphicsStateCollectionSerializerModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.GridModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.GridModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.HierarchyCoreModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.HierarchyCoreModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.HierarchyModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.HierarchyModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.HotReloadModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.HotReloadModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.IdentifiersModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.IdentifiersModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.ImageConversionModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.ImageConversionModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.IMGUIModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.IMGUIModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.InputForUIModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.InputForUIModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.InputLegacyModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.InputLegacyModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.InputModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.InputModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.JSONSerializeModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.JSONSerializeModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.LocalizationModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.LocalizationModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.MarshallingModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.MarshallingModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.MultiplayerModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.MultiplayerModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.ParticleSystemModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.ParticleSystemModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.PerformanceReportingModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.PerformanceReportingModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.Physics2DModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.Physics2DModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.PhysicsBackendPhysXModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.PhysicsBackendPhysXModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.PhysicsModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.PhysicsModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.PropertiesModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.PropertiesModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.Purchasing.AppleCore"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.Purchasing.AppleCore.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.Purchasing.AppleMacosStub"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.Purchasing.AppleMacosStub.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.Purchasing.AppleStub"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.Purchasing.AppleStub.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.Purchasing"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.Purchasing.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.Purchasing.SecurityCore"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.Purchasing.SecurityCore.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.Purchasing.SecurityStub"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.Purchasing.SecurityStub.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.Purchasing.Stores"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.Purchasing.Stores.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.Purchasing.WinRTCore"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.Purchasing.WinRTCore.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.Purchasing.WinRTStub"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.Purchasing.WinRTStub.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.RenderAs2DModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.RenderAs2DModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.ScreenCaptureModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.ScreenCaptureModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.ShaderRuntimeModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.ShaderRuntimeModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.ShaderVariantAnalyticsModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.ShaderVariantAnalyticsModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.SharedInternalsModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.SharedInternalsModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.SpriteMaskModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.SpriteMaskModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.SpriteShapeModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.SpriteShapeModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.StreamingModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.StreamingModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.SubstanceModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.SubstanceModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.SubsystemsModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.SubsystemsModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.TerrainModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.TerrainModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.TerrainPhysicsModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.TerrainPhysicsModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.TextCoreFontEngineModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.TextCoreFontEngineModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.TextCoreTextEngineModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.TextCoreTextEngineModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.TextRenderingModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.TextRenderingModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.TilemapModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.TilemapModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.TLSModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.TLSModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.UI"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.UI.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.UIElementsModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.UIElementsModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.UIModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.UIModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.UmbraModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.UmbraModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.UnityAnalyticsCommonModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.UnityAnalyticsCommonModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.UnityAnalyticsModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.UnityAnalyticsModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.UnityConnectModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.UnityConnectModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.UnityConsentModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.UnityConsentModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.UnityCurlModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.UnityCurlModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.UnityWebRequestAssetBundleModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.UnityWebRequestAssetBundleModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.UnityWebRequestAudioModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.UnityWebRequestAudioModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.UnityWebRequestModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.UnityWebRequestModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.UnityWebRequestTextureModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.UnityWebRequestTextureModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.UnityWebRequestWWWModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.UnityWebRequestWWWModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.VectorGraphicsModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.VectorGraphicsModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.VehiclesModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.VehiclesModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.VFXModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.VFXModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.VideoModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.VideoModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.VirtualTexturingModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.VirtualTexturingModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.VRModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.VRModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.WindModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.WindModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.XRModule"><HintPath>$(GameRoot)\BepInEx\interop\UnityEngine.XRModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="ModularSkillScripts"><HintPath>$(GameRoot)\BepInEx\plugins\ModularSkillScripts.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
</Project>
